### ISSUE TITLE
Crashes when using `lintDirtyModulesOnly` and webpack 5.beta0

### ISSUE THREAD

**Issue by thasmo** [webpack-contrib/stylelint-webpack-plugin#187]
### Expected Behavior
Does not crash on successive webpack builds in watch mode.

### Actual Behavior
Crashes on successive webpack builds in watch mode; not on the initial watch build tho.

### Call Stack
```sh
TypeError: Cannot read property 'entries' of undefined
at LintDirtyModulesPlugin.getChangedFiles (C:\Users\user\Projects\project\node_modules\stylelint-webpack-plugin\dist\LintDirtyModulesPlugin.js:53:56)
at LintDirtyModulesPlugin.apply (C:\Users\user\Projects\project\node_modules\stylelint-webpack-plugin\dist\LintDirtyModulesPlugin.js:34:31)
at compiler.hooks.emit.tapAsync (C:\Users\user\Projects\project\node_modules\stylelint-webpack-plugin\dist\index.js:38:19)
at _next1 (eval at create (C:\Users\user\Projects\project\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:56:1)
at _err1 (eval at create (C:\Users\user\Projects\project\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:82:1)
at WebpackAssetsManifest.handleEmit (C:\Users\user\Projects\project\node_modules\webpack-assets-manifest\src\WebpackAssetsManifest.js:486:5)
at Hook.eval [as callAsync] (eval at create (C:\Users\user\Projects\project\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:78:1)
at Compiler.emitAssets (C:\Users\user\Projects\project\node_modules\webpack\lib\Compiler.js:536:19)
at process.nextTick (C:\Users\user\Projects\project\node_modules\webpack\lib\Watching.js:75:21)
at process._tickCallback (internal/process/next_tick.js:61:11)
````

### How Do We Reproduce?
Use `webpack` 5.beta0 and `stylelint-webpack-plugin` with the `lintDirtyModulesOnly` option enabled and run `webpack` in watch mode and after the initial build, change a file which should trigger a rebuild - this time the plugin will crash.

### Environment
- OS: Windows 10
- Node: 10
- NPM: 6.11
- webpack: 5.beta0
- stylelint-webpack-plugin: 1.0.2

**Comment by vankop** [comment]
I will take a look on this

**Comment by sokra** [comment]
compilation.fileTimestamps has been removed in webpack 5.

see also https://github.com/webpack/changelog-v5#compilationfilesysteminfo
