### ISSUE TITLE
stylelint 11.0.0+ : TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by akoidan** [webpack-contrib/stylelint-webpack-plugin#188]
- Operating System: Archlinux (doesn't matter)
- Node Version: Doesn't matter (tested with v10.16.3, 12.10.0)
- NPM Version: 6.9.0 (doesn't matter)
- webpack Version: 4.41.1
- stylelint-webpack-plugin Version: 1.0.2

### Expected Behavior

Code compiles w/o errors

### Actual Behavior

```text
TypeError: Cannot read property 'start' of undefined
    at LocalFixer.node (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/parse-style.js:35:27)
    at root.walk.node (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/parse-style.js:41:9)
    at /home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss/lib/container.js:135:18
    at Root.each (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss/lib/container.js:131:17)
    at LocalFixer.root (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/parse-style.js:40:8)
    at LocalFixer.parse (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/parse-style.js:69:9)
    at parseStyle (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/parse-style.js:88:39)
    at styles.sort.forEach.style (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/parse-style.js:103:17)
    at Array.forEach (<anonymous>)
    at parseStyle (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/parse-style.js:102:6)
    at processor (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/processor.js:26:9)
    at Object.parse (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss-syntax/parse.js:25:10)
    at new LazyResult (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/postcss/lib/lazy-result.js:60:16)
    at getCode.then.code (/home/andrew/WebstormProjects/vue-webpack-typescript/node_modules/stylelint/lib/getPostcssResult.js:127:22)
```

### Code

Not configuration related.

### How Do We Reproduce?
- Check the branch [stylelint-webpack-plugin-error](https://github.com/akoidan/vue-webpack-typescript/tree/stylelint-webpack-plugin-error)
- Use `stylelint-webpack-plugin` with `stylelint` >= `^11.0.0`. If you downgrade stylelint to `10.1.0` it works fine. 
- Related issue to configuration change is [here](https://github.com/stylelint/stylelint/issues/678)

**Comment by vankop** [comment]
@akoidan could you try run just stylelint without this plugin? maybe this issue related to stylelint instead of webpack plugin

**Comment by akoidan** [comment]
@vankop this issue IS related to stylelint, since that changed the API, and it doesn't work with the same code as it did before. The description is in related issue I attached. I guess it's either worth changing the README, specifying the version of stylelint, either support the latest version of stylelint that you have in the readme.

**Comment by ricardogobbosouza** [comment]
@akoidan I couldn't understand the problem and I couldn't reproduce either

**Comment by akoidan** [comment]
> @akoidan I couldn't understand the problem and I couldn't reproduce either

I attached the repo and mentioned it in the description. Does it work on your PC? https://github.com/akoidan/vue-webpack-typescript/tree/stylelint-webpack-plugin-error , mind the branch

**Comment by ricardogobbosouza** [comment]
@akoidan There are several errors and warnings, but none related to this plugin.

**Comment by akoidan** [comment]
@ricardogobbosouza yeah, I think it's rather related to `scss` syntax https://github.com/kristerkari/stylelint-scss/issues/380

**Comment by ricardogobbosouza** [comment]
Forwaded to AleshaOleg/postcss-sass#120
